/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.alpha_aids_calculator;

/**
 *
 * @author tech
 */
public class Calculator extends javax.swing.JFrame {
     
    double num1=0,num2=0;
    String operator = null;    
    
    
    /** Creates new form Calculator */
    public Calculator() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton11 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        v7 = new javax.swing.JButton();
        v8 = new javax.swing.JButton();
        v9 = new javax.swing.JButton();
        vdiv = new javax.swing.JButton();
        v4 = new javax.swing.JButton();
        v5 = new javax.swing.JButton();
        v6 = new javax.swing.JButton();
        vmultiply = new javax.swing.JButton();
        vadd = new javax.swing.JButton();
        v3 = new javax.swing.JButton();
        v2 = new javax.swing.JButton();
        v1 = new javax.swing.JButton();
        v0 = new javax.swing.JButton();
        vdot = new javax.swing.JButton();
        vequal = new javax.swing.JButton();
        vsubtract = new javax.swing.JButton();
        vclear = new javax.swing.JButton();
        vback = new javax.swing.JButton();

        jButton11.setText("jButton11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 153));

        jTextField1.setBackground(new java.awt.Color(255, 153, 153));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jTextField1.setText("Created By Priyanshi Sharma");

        v7.setBackground(new java.awt.Color(153, 153, 153));
        v7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        v7.setText("7");
        v7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v7ActionPerformed(evt);
            }
        });

        v8.setBackground(new java.awt.Color(153, 153, 153));
        v8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        v8.setText("8");
        v8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v8ActionPerformed(evt);
            }
        });

        v9.setBackground(new java.awt.Color(153, 153, 153));
        v9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        v9.setText("9");
        v9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v9ActionPerformed(evt);
            }
        });

        vdiv.setBackground(new java.awt.Color(153, 153, 153));
        vdiv.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vdiv.setText("/");
        vdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vdivActionPerformed(evt);
            }
        });

        v4.setBackground(new java.awt.Color(153, 153, 153));
        v4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        v4.setText("4");
        v4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v4ActionPerformed(evt);
            }
        });

        v5.setBackground(new java.awt.Color(153, 153, 153));
        v5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        v5.setText("5");
        v5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v5ActionPerformed(evt);
            }
        });

        v6.setBackground(new java.awt.Color(153, 153, 153));
        v6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        v6.setText("6");
        v6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v6ActionPerformed(evt);
            }
        });

        vmultiply.setBackground(new java.awt.Color(153, 153, 153));
        vmultiply.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vmultiply.setText("*");
        vmultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vmultiplyActionPerformed(evt);
            }
        });

        vadd.setBackground(new java.awt.Color(153, 153, 153));
        vadd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vadd.setText("+");
        vadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaddActionPerformed(evt);
            }
        });

        v3.setBackground(new java.awt.Color(153, 153, 153));
        v3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        v3.setText("3");
        v3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v3ActionPerformed(evt);
            }
        });

        v2.setBackground(new java.awt.Color(153, 153, 153));
        v2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        v2.setText("2");
        v2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v2ActionPerformed(evt);
            }
        });

        v1.setBackground(new java.awt.Color(153, 153, 153));
        v1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        v1.setText("1");
        v1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v1ActionPerformed(evt);
            }
        });

        v0.setBackground(new java.awt.Color(153, 153, 153));
        v0.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        v0.setText("0");
        v0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v0ActionPerformed(evt);
            }
        });

        vdot.setBackground(new java.awt.Color(153, 153, 153));
        vdot.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vdot.setText(".");
        vdot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vdotActionPerformed(evt);
            }
        });

        vequal.setBackground(new java.awt.Color(153, 153, 153));
        vequal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vequal.setText("=");
        vequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vequalActionPerformed(evt);
            }
        });

        vsubtract.setBackground(new java.awt.Color(153, 153, 153));
        vsubtract.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vsubtract.setText("-");
        vsubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vsubtractActionPerformed(evt);
            }
        });

        vclear.setBackground(new java.awt.Color(255, 153, 204));
        vclear.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        vclear.setText("Clear");
        vclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vclearActionPerformed(evt);
            }
        });

        vback.setBackground(new java.awt.Color(153, 153, 255));
        vback.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vback.setText("Back");
        vback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(v7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(v8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(v4, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                            .addComponent(v1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(v0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(v5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(v2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vdot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(vclear)))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vback)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(v9, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                            .addComponent(v3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(v6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(vequal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(vadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(vmultiply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(vdiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(vsubtract, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(vdiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(v7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(v8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(v9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(v6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vmultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(v4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(v5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(v2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(v3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vadd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v0, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vdot, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vequal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vsubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vclear)
                    .addComponent(vback))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void v7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v7ActionPerformed
        t1.setText(t1.getText()+"7");        // TODO add your handling code here:
    }//GEN-LAST:event_v7ActionPerformed

    private void v8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v8ActionPerformed
         t1.setText(t1.getText()+"8");         // TODO add your handling code here:
    }//GEN-LAST:event_v8ActionPerformed

    private void v9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v9ActionPerformed
         t1.setText(t1.getText()+"9");         // TODO add your handling code here:
    }//GEN-LAST:event_v9ActionPerformed

    private void v4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v4ActionPerformed
         t1.setText(t1.getText()+"4");         // TODO add your handling code here:
    }//GEN-LAST:event_v4ActionPerformed

    private void v5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v5ActionPerformed
         t1.setText(t1.getText()+"5");         // TODO add your handling code here:
    }//GEN-LAST:event_v5ActionPerformed

    private void v6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v6ActionPerformed
         t1.setText(t1.getText()+"6");         // TODO add your handling code here:
    }//GEN-LAST:event_v6ActionPerformed

    private void v1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v1ActionPerformed
         t1.setText(t1.getText()+"1");         // TODO add your handling code here:
    }//GEN-LAST:event_v1ActionPerformed

    private void v2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v2ActionPerformed
         t1.setText(t1.getText()+"2");         // TODO add your handling code here:
    }//GEN-LAST:event_v2ActionPerformed

    private void v3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v3ActionPerformed
         t1.setText(t1.getText()+"3");         // TODO add your handling code here:
    }//GEN-LAST:event_v3ActionPerformed

    private void v0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v0ActionPerformed
         t1.setText(t1.getText()+"0");         // TODO add your handling code here:
    }//GEN-LAST:event_v0ActionPerformed

    private void vdotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vdotActionPerformed
         t1.setText(t1.getText()+".");         // TODO add your handling code here:
    }//GEN-LAST:event_vdotActionPerformed

    private void vdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vdivActionPerformed
        num1=Double.parseDouble(t1.getText());
        t1.setText("");
        operator="/";        // TODO add your handling code here:
    }//GEN-LAST:event_vdivActionPerformed

    private void vmultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vmultiplyActionPerformed
        num1=Double.parseDouble(t1.getText());
        t1.setText("");
        operator="*";         // TODO add your handling code here:
    }//GEN-LAST:event_vmultiplyActionPerformed

    private void vaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaddActionPerformed
        num1=Double.parseDouble(t1.getText());
        t1.setText("");
        operator="+";         // TODO add your handling code here:
    }//GEN-LAST:event_vaddActionPerformed

    private void vsubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vsubtractActionPerformed
        num1=Double.parseDouble(t1.getText());
        t1.setText("");
        operator="-";         // TODO add your handling code here:
    }//GEN-LAST:event_vsubtractActionPerformed

    private void vequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vequalActionPerformed
        num2=Double.parseDouble(t1.getText());
        double ans=0;
        if(operator=="+"){
            ans=num1+num2;
        }
        if(operator=="-"){
            ans=num1-num2;
        }
        if(operator=="*"){
            ans=num1*num2;
        }
        if(operator=="/"){
            ans=num1/num2;
        }
        t1.setText(""+ans);
        operator=null;
// TODO add your handling code here:
    }//GEN-LAST:event_vequalActionPerformed

    private void vclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vclearActionPerformed
        t1.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_vclearActionPerformed

    private void vbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vbackActionPerformed
        String str=t1.getText();
        t1.setText(str.substring(0,str.length()-1));        // TODO add your handling code here:
    }//GEN-LAST:event_vbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton11;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField t1;
    private javax.swing.JButton v0;
    private javax.swing.JButton v1;
    private javax.swing.JButton v2;
    private javax.swing.JButton v3;
    private javax.swing.JButton v4;
    private javax.swing.JButton v5;
    private javax.swing.JButton v6;
    private javax.swing.JButton v7;
    private javax.swing.JButton v8;
    private javax.swing.JButton v9;
    private javax.swing.JButton vadd;
    private javax.swing.JButton vback;
    private javax.swing.JButton vclear;
    private javax.swing.JButton vdiv;
    private javax.swing.JButton vdot;
    private javax.swing.JButton vequal;
    private javax.swing.JButton vmultiply;
    private javax.swing.JButton vsubtract;
    // End of variables declaration//GEN-END:variables

}
